sudo: false
language: cpp
before_install: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
install:
        - export CXX="g++-4.8" CC="gcc-4.7";
script: make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
