sudo: false
language: cpp
install:
        - export CXX="g++-4.8" CC="gcc-4.8";
        - pip install --user cpp-coveralls;
        - ./get-cpputest.sh
script:
  - make
after_success:
  - coveralls --gcov gcov-4.8 --exclude env --exclude examples --exclude tests/AllTests.cpp --exclude tests/TestOption.cpp --gcov-options '\-lp'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
