sudo: false
language: cpp
install:
        - export CXX="g++-4.8" CC="gcc-4.7";
script: make
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
